---
name: jira_connect_create_branch
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/66032
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/336191
milestone: '14.1'
type: development
group: group::ecosystem
default_enabled: false
