---
name: jira_connect_oauth
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/67895
rollout_issue_url:
milestone: '14.2'
type: development
group: group::integrations
default_enabled: false
