---
name: pipeline_editor_mini_graph
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/71622
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/342217
milestone: '14.4'
type: development
group: group::pipeline authoring
default_enabled: false
