---
name: seat_usage_export
introduced_by_url:
rollout_issue_url: # https://gitlab.com/gitlab-org/gitlab/-/issues/new?issue%5Btitle%5D=%5BFeature+flag%5D+Rollout+of+%60seat_usage_export%60&issuable_template=Feature+Flag+Roll+Out
milestone: '14.2'
type: development
group: group::utilization
default_enabled: false
