---
key_path: usage_activity_by_stage_monthly.release.releases_with_group_milestones
description: Unique users creating releases with group milestones associated
product_section: ops
product_stage: release
product_group: 'group::release'
product_category: Release Orchestration
value_type: number
status: implemented
milestone: "14.2"
introduced_by_url: 'https://gitlab.com/gitlab-org/gitlab/-/merge_requests/66063'
time_frame: 28d
data_source: database
instrumentation_class: 'CountUsersAssociatingGroupMilestonesToReleasesMetric'
data_category: Optional
distribution:
- ee
tier:
- premium
- ultimate
