---
name: ecomm_instrumentation_google_analytics_cookies
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/71242
rollout_issue_url:
milestone: '14.4'
type: ops
group: group::product intelligence
default_enabled: false
